### PR TITLE
Fix unable to get TGVMax results, adding connection to account

### PR DESCRIPTION
**Pull request by TitCaz**
I fixed the issue with TGVMax card.

**Bug before**
[https://github.com/tducret/trainline-python/issues/16](url)

**What I did**
I added the log in with a business trainline account (which is free : https://www.trainline.fr/business), before search.
It doesn't make outdated the old requests with this package, but to be able to have TGVMax results, we have to make these commands : 

~~~ python
#Login and password of your business trainline account
trainline_sess = Trainline('YOUREMAILACCOUNT','YOURPASSWORD')

# Birthdate, firstname and lastname must the same as the passenger created in your business trainline account, for
# who you have associated the TGVMax card (you can find it there : https://www.trainline.fr/organization/members)
TGVMaxPassenger = Passenger(birthdate="BIRTHDATESPASSENGER",
firstname='FIRSTNAMESPASSENGER',
lastname='LASTNAMESPASSENGER',
trainline_session=trainline_sess)
results = search(
passengers=[TGVMaxPassenger],
departure_station='Lyon',
arrival_station='Paris',
from_date="11/11/2020 12:00",
to_date="12/11/2020 20:00")
~~~

You can add other passengers, even if they haven't TGVMax card, but they must also be added with these parameters : Passenger(birthdate="BIRTHDATESPASSENGER", firstname='FIRSTNAMESPASSENGER', lastname='LASTNAMESPASSENGER', trainline_session=trainline_sess), and also be created in your business trainline account.

### CODE REVIEW

**Comment by antoinevth** [comment]
@tducret, what do you think of this PR? Any ETA for a merge?

**Comment by TitCaz** [comment]
Thank you @tducret .
Is it possible to update the package on pypi too, to have new updates easily ?
Thank's by advance,

**Comment by tducret** [comment]
I'd want to but the travis build is stuck in the queue... > https://travis-ci.org/github/tducret/trainline-python/builds/738371000
I even updated the tests that were obsolete for this release.

**Comment by tducret** [comment]
Well, that's strange. I uploaded it on pypi manually (`v0.1.2`).
Could you please upgrade and give it a try @TitCaz ?

**Pull request merged**
