### PR TITLE
Update setup.py

### LINKED ISSUE #13: I can't install trainline using pip3
* trainline version: latest
* Python version: 3.8
* Operating System: OSX

### Description

I can't install trainline using pip3

### What I Did

```$ pip3 install -U trainline --user
Collecting trainline
  Using cached trainline-0.1.1.tar.gz (279 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lr/0m8k26c90rs3zfhdq2018rt40000gn/T/pip-install-654dg46b/trainline/setup.py'"'"'; __file__='"'"'/private/var/folders/lr/0m8k26c90rs3zfhdq2018rt40000gn/T/pip-install-654dg46b/trainline/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/lr/0m8k26c90rs3zfhdq2018rt40000gn/T/pip-pip-egg-info-dsamo052
         cwd: /private/var/folders/lr/0m8k26c90rs3zfhdq2018rt40000gn/T/pip-install-654dg46b/trainline/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lr/0m8k26c90rs3zfhdq2018rt40000gn/T/pip-install-654dg46b/trainline/setup.py", line 22, in <module>
        requirements = [str(ir.req) for ir in install_reqs]
      File "/private/var/folders/lr/0m8k26c90rs3zfhdq2018rt40000gn/T/pip-install-654dg46b/trainline/setup.py", line 22, in <listcomp>
        requirements = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

### PR DESCRIPTION
**Pull request by antoinevth**
This update fix #13

### CODE REVIEW

**Comment by tducret** [comment]
Thanks

**Comment by VivienGiraud** [comment]
@antoinevth Many thanks ! Was looking to do it on spare time :) 
@tducret Any ETA on when it could be available on pip ?

**Comment by VivienGiraud** [comment]
```pip3 install git+git://github.com/tducret/trainline-python.git@master```

Can help

**Comment by tducret** [comment]
@VivienGiraud I prepared the release rightaway, but the unit tests are not passing anymore :(
Consequently travis didn't push the package on pypi.org.

**Comment by VivienGiraud** [comment]
Ho OK, thanks @tducret for the info.

**Pull request merged**
